#!/bin/bash

###########
# MKMAKE #
###########

case $1 in

	# C Makefile
	c)
		echo "main: clean compile exec" > makefile;
		echo "clean:" >> makefile;
		echo "	@rm -f *.o" >> makefile;
		echo "compile:" >> makefile;
        	echo "	@gcc -g -c *.c" >> makefile;
        	echo "	@gcc *.o -lpthread -g -o \"${PWD##*/}\"" >> makefile;
        	echo "exec:" >> makefile;
        	echo "	@./${PWD##*/}" >> makefile;
		echo "@ Makefile generated. @";
		;;

	# Java makefile
  	java)
		echo "Main-Class: ${PWD##*/}.${PWD##*/}" > manifest.txt;
		echo "main: compile exec" > makefile;
		echo "compile: *.java" >> makefile;
		echo "	@javac -d . *.java" >> makefile;
		echo "	@jar -cvfm ${PWD##*/}.jar manifest.txt ${PWD##*/}*" >> makefile;
		echo "exec:" >> makefile;
		echo "	@java -jar ${PWD##*/}.jar" >> makefile;
		echo "@ Makefile and manifest generated. @";
		;;

	# Nodejs makefile
	nodejs)
		echo "main: exec" > makefile;
		echo "exec:" >> makefile;
		echo "	@nodejs ${PWD##*/}.js" >> makefile;
		echo "@ Makefile generated. @";
		;;

	# Prolog makefile
	prolog)
		echo "main: exec" > makefile;
		echo "exec:" >> makefile;
		echo "	@swipl -q -s ${PWD##*/}.pl -t ${PWD##*/}" >> makefile;
		echo "@ Makefile generated. @";
		;;

	# Python makefile
	python)
		echo "main: exec" > makefile;
		echo "exec:" >> makefile;
		echo "	@python ${PWD##*/}.py" >> makefile;
		echo "@ Makefile generated. @";
		;;

	# (invalid option)
	*)
		echo "@ Invalid option. @";
		echo "@ Try again. (example: mkmake java) @";
		;;

esac
